baseURL = 'https://philotfarnsworth.github.io/Portfolio/'
languageCode = 'en-us'
enableRobotsTXT = 'true'
title = "Michael Gardner - In His Own Words"

## This may not be necessary this time
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = 'true'

[outputs]
  page = ['HTML', 'JSON']

[params]
  description = "Michael Gardner plays his greatest hits!"
  keywords = "Portfolio, Career, Web Development, HTML5, CSS3, Javascript, Go, Golang, Hugo, Developer, Software, Hire Me"
  author = "Michael Gardner"
  email = "Idodevthings@gmail.com"
  linkedIn = "https://www.linkedin.com/in/michael-gardner-az"
  github = "PhiloTFarnsworth"
  year = "2022"
  background = "desert.svg"
  bio = "An aspiring developer in Tucson, AZ, I seek to leverage my skills to create unique and interesting digital experiences."
  quote = "Give me a fulcrum and some documentation, and I will move the world"
  contactPatter = "Send comments, questions and solicitations to"
  ## TODO: Font Decisions
  fonts = []

  

[_build]
  publishResources = true

